spring.application.name=contract-tesing-provider

server.port=8080

#logging.level.org.springframework=DEBUG
logging.level.au.com.dius.pact.provider=DEBUG

logging.file.name=C:\\temp\\logs\\contract-api.log